# Generated by Django 2.2.15 on 2020-11-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_short_url', '0002_auto_20180107_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='status',
            field=models.BooleanField(default=True, help_text='Status', verbose_name='status'),
        ),
    ]
